### ISSUE TITLE
container crashing after a while

### ISSUE THREAD

**Issue by kamilmirza** [jrd/docker-nginx-fancy#1]
when I restart the container is works for a bit and then after a while it starts to crash
have not changed anything inside the container
here's the `docker log`
```
nginx -g daemon off;
2019/07/31 16:01:03 [emerg] 1#1: module "ngx_http_fancyindex_module" is already loaded in /etc/nginx/load.d/fancyindex.conf:1
nginx: [emerg] module "ngx_http_fancyindex_module" is already loaded in /etc/nginx/load.d/fancyindex.conf:1
nginx -g daemon off;
2019/07/31 16:01:11 [emerg] 1#1: module "ngx_http_fancyindex_module" is already loaded in /etc/nginx/load.d/fancyindex.conf:1
nginx: [emerg] module "ngx_http_fancyindex_module" is already loaded in /etc/nginx/load.d/fancyindex.conf:1
nginx -g daemon off;
2019/07/31 16:01:15 [emerg] 1#1: module "ngx_http_fancyindex_module" is already loaded in /etc/nginx/load.d/fancyindex.conf:1
nginx: [emerg] module "ngx_http_fancyindex_module" is already loaded in /etc/nginx/load.d/fancyindex.conf:1
```
here my `docker-compose.yml`
```
fancyindex:
    container_name: fancyindex
    image: jrdasm/nginx-fancy
    restart: always
    ports:
      - 8782:80
    volumes:
      - /var/www/html/:/usr/share/nginx/html/ # Location you want to index
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

**Comment by jrd** [comment]
Yeah, it seems that the container crashed after less than 5 seconds.
The `restart: always` directive in your compose file will make it restarts but it's a concern.

Unfortunately, I cannot do anything about it: this container just compile the module and pack it to use it easily but I didn't change anything in the module source code and I even didn't read it.

So better report this error to `nginx-fancy-module` directly: https://github.com/aperezdc/ngx-fancyindex/issues

If this has anything related to the way I compile it, please re-open.

**Comment by mountainash** [comment]
You'll get this if you have `fancyindex on;` in your nginx `.conf`. Just remove that line and it should `docker-compose up` without problems.
